### ISSUE TITLE
r2s 4.15稳定版固件内存问题

### ISSUE THREAD

**Issue by 0xDion** [DHDAXCW/NanoPi-R2S#85]
![捕获](https://user-images.githubusercontent.com/85660775/163804710-b3252076-9f60-4861-bfad-6842c51d4e2b.PNG)

**Comment by Loukky** [comment]
我的没有这个问题
https://imgs3.loukky.com/imgs/2022/04/20/6ec4af045f62403e.png

**Comment by sldgrbk** [comment]
重新刷固件即可
